name: Validate asset images

# **What it does**: Run ./src/assets/scripts/validate-asset-images.js on all images in assets/
# **Why we have it**: To protect from innocent and potentially malicious bad image assets
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'assets/**'

permissions:
  contents: read

jobs:
  validate-asset-images:
    if: ${{ github.repository == 'github/docs-internal' || github.repository == 'github/docs' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@8459bc0c7e3759cdf591f513d9f141a95fef0a8f # v4.0.0

      - uses: ./.github/actions/node-npm-setup

      - name: Validate all asset images
        run: src/assets/scripts/validate-asset-images.js
